#!/bin/bash

sudo apt update

sudo apt install -y unzip wget

wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip

unzip terraform_*_linux_*.zip

sudo mv terraform /usr/location/bin

rm terraform_*_linux_*.zip

echo Terraform was installed
terraform --version
